stages:
  - build
  - scan
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: node:16.16-alpine3.15
  stage: build
  tags:
    - node-docker
  script:
    - npm i
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
      - .env
    expire_in: 1 days

linter:
  image: node:16.16-alpine3.15
  stage: scan
  dependencies:
    - build
  tags:
    - node-docker
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @vue/cli-service
    - vue-cli-service lint

# tests:
#   image: node:16.16-alpine3.15
#   stage: scan
#   dependencies:
#     - build
#   tags:
#     - node-docker
#   cache:
#     paths:
#       - node_modules/
#   script:
#     - npm run test:unit

deploy:
  stage: deploy
  only:
    - dev
  tags:
    - node-shell
  script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "Deploying branch - $CI_COMMIT_BRANCH"
    - cd /var/mobile && git checkout "$CI_COMMIT_BRANCH" && git reset --hard "$CI_COMMIT_BRANCH" && git pull origin "$CI_COMMIT_BRANCH"
    - cd /var/mobile && docker-compose stop
    - cd /var/mobile && docker-compose pull
    - cd /var/mobile && docker-compose run --rm node-app npm i
    - cd /var/mobile && docker-compose run --rm node-app npm run build
    - cd /var/mobile && docker-compose up -d
