version: '3'

services:
  node-app:
    image: node:16.16-alpine3.15
    volumes:
      - ./:/var/www/
    working_dir: /var/www/

  node-nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - 8080:80