export enum EntitiesEnum {
  User = "PROFILE",
  Login = "LOGIN",
  Register = "REGISTER",
  Quizz = "QUIZZ",
  Facilities = "FACILITIES",
  Facility = "FACILITY",
  Trainers = "TRAINERS",
  Trainer = "TRAINER",
}

export const dummyPasses = [
  { 
    id: "1",
    title: "Fantastic Gym",
    imgSrc: "assets/backgrounds/Gym_3.png",
    location: "Wall Street, 24",
    days: "7 days left",
    upcomingType: "Premium",
  },
  { 
    id: "2",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  },
  { 
    id: "3",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  },
  { 
    id: "4",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  },
  { 
    id: "5",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  }
]
export const dummyDropins = [
  { 
    id: "1",
    title: "Fantastic Gym",
    imgSrc: "assets/backgrounds/Gym_3.png",
    location: "Wall Street, 24",
    days: "7 days left",
    upcomingType: "7 Days",
  },
  { 
    id: "2",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  },
  { 
    id: "3",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  },
  { 
    id: "4",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  },
  { 
    id: "5",
    title: "Diamond Gym",
    imgSrc: "assets/backgrounds/Gym_1.png",
    location: "Wall Street, 24",
    days: "0 days left",
    upcomingType: "Expired",
  }
]
export const dummyTraings = [
  { 
    id: "1",
    title: "Tamra Dae",
    subtitle: "17 june",
    imgSrc: "assets/backgrounds/Gym_3.png",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "2",
    title: "Tamra Dae",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "3",
    title: "Tamra Dae",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "4",
    title: "Tamra Dae",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "5",
    title: "Jennifer James",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "6",
    title: "Jennifer James",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "7",
    title: "Jennifer James",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  },
  { 
    id: "8",
    title: "Jennifer James",
    imgSrc: "assets/backgrounds/Gym_1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
  }
];

export const upcomingEvent = [
  {
    id: "1",
    title: "Food festival",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Upcoming",
  },
  {
    id: "2",
    title: "Food festival",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Upcoming",
  },
  {
    id: "3",
    title: "Food festival",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Finished",
  },
  {
    id: "4",
    title: "Food festival",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Finished",
  },
  {
    id: "5",
    title: "Run competition",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Upcoming",
  },
  {
    id: "6",
    title: "Food festival",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Upcoming",
  },
  {
    id: "7",
    title: "Food festival",
    imgSrc: "assets/backgrounds/food1.png",
    subtitle: "17 june",
    location: "Summer Gym, Wall Street, 24",
    upcomingType: "Upcoming",
  },
]
