<template>
  <div>
    <ion-title class="title">
      Password and Security
    </ion-title>
    <div class="content-box">
      <div class="column-box">
        <ion-title class="content-box__title">
          Password
        </ion-title>
        <ion-label>Follow steps to change your password</ion-label>
        <div class="content-box__line"/>
        <div class="input-box">
          <div>
            <ion-label class="text-label">Old Password</ion-label>
            <ion-input placeholder="Enter old password" class="custom-input"/>
          </div>
          <div>
            <ion-label class="text-label">New Password</ion-label>
            <ion-input placeholder="Enter new password" class="custom-input"/>
          </div>
          <div>
            <ion-label class="text-label">Confirm Password</ion-label>
            <ion-input placeholder="Confirm password" class="custom-input"/>
          </div>
        </div>
      </div>
      <div class="d-flex align-items-center justify-content-end save-box">
        <ion-button>Save</ion-button>
      </div>
    </div>
    <div class="content-box column-box">
      <div class="d-flex justify-content-between align-items-center ">
        <div>
          <ion-title class="content-box__title">
            Two-factor Authentication
          </ion-title>
          <ion-label>Add an extra later of security to block unauthorized access and protect your account.</ion-label>
        </div>
        <ion-button>Enable</ion-button>
      </div>
      <div class="content-box__line"/>
      <div class="d-flex justify-content-between aling-items-center justify-content-center option-box">
        <div>
          <ion-text>Authentication app code</ion-text><br/>
          <ion-label color="medium">Enter a code generated by authenticator app to confirm it’s you.</ion-label>
        </div>
        <ion-toggle></ion-toggle>
      </div>
      <div class="d-flex justify-content-between aling-items-center justify-content-center option-box">
        <div>
          <ion-text>Sms recovery</ion-text><br/>
          <ion-label color="medium">Receive a six digit code by text message to confirm it’s you</ion-label>
        </div>
        <ion-toggle></ion-toggle>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, watch, onMounted, ref, inject } from "vue";
import {
	IonTitle,
  IonButton,
  IonLabel,
  IonInput,
  IonToggle,
  PickerColumnOption,
  PickerOptions,
	IonGrid,
	IonRow,
	IonCol
} from "@ionic/vue";
import { useRouter } from "vue-router";
import { minutesDuration } from "@/const/minutes-durations";
import { useField } from "vee-validate";
import { EntitiesEnum } from "@/const/entities";
import { useWorkoutsStore } from "../../../../trainers/store/workouts";
import { requiredFieldSchema } from "@/validations/authValidations";
import WheelPicker from "@/general/components/blocks/WheelPicker.vue";
import { v4 as uuidv4 } from "uuid";
import { FilePreloadDocument } from "@/generated/graphql";
import { useMutation } from "@vue/apollo-composable";
import { dataURItoFile } from "@/utils/fileUtils";
import ChooseBlock from "@/general/components/blocks/Choose.vue";
import PhotoLoader from "@/general/components/blocks/PhotoLoader.vue";
import { Emitter, EventType } from "mitt";

const percentLoaded = ref(0);

const router = useRouter();

const store = useWorkoutsStore();

</script>

<style lang="scss" scoped>

.title {
  padding: 0;
  font-size: 28px;
  line-height: 1.3;
  font-weight: 400;
  margin-bottom: 24px;
}
.top-buttons {
  display: flex;
  justify-content: space-between;
}
.dashboard-btn {
  margin-top: 10px;
}
.content-box {
  background-color: #0000001a;
  margin-top: 20px;
  margin-bottom: 20px;
  padding-top: 23px;
  padding-left: 35px;
  padding-right: 6px;
  padding-bottom: 20px;

  &__top {
    display: flex;
    padding-right: 13px;
  }

  &__title {
    padding: 0;
  }

  &__button {
    max-width: 73px;
    max-height: 36px;
  }

  &__line {
    margin-left: -20px;
    height: 2px;
    background-color: var(--gray-600);
  }
}
.column-box {
  display: flex;
  flex-direction: column;
  gap: 14px;
}
.save-box {
  padding-top: 26px;
  padding-right: 20px;
}
.input-box {
  display: flex;
  flex-direction: column;
  gap: 10px;
  max-width: 473px;
}
.text-label {
  color: #FFFFFF6a;
}
.text-value {
  color: var(--grey-text);
  background-color: var(--gray-600);
  font: 600 18px/1 var(--ion-font-family);
}
.option-box {
  padding: 10px;
}

ion-button {
  color: var(--ion-color-medium);
  max-height: 40px;
}
ion-input {
  border: solid;
  border-color: #FFFFFF6a;
  border-radius: 8px;
  border-width: 1px;
  margin-top: 6px;
  margin-bottom: 6px;
  --placeholder-color: var(--ion-color-medium);
}
ion-label {
  font: 400 14px/1 var(--ion-font-family);
}
ion-toggle {
  height: 28px;
  width: 48px;
  padding-bottom: 0;
  padding-top: 0;
  --handle-height: 24px;
  --handle-width: 24px;
  --handle-spacing: 3px;
  --background: var(--gray-600);
  --background-checked: var(--gold);
  --handle-background: var(--gray-700);
  --handle-background-checked: var(--gray-700);
}
</style>
