<template>
  <div>
    <ion-title class="title">
      Password and Security
    </ion-title>
    <div class="content-box">
      <div class="column-box">
        <ion-title class="content-box__title">
          Password
        </ion-title>
        <ion-label>Follow steps to change your password</ion-label>
        <div class="content-box__line"/>
        <div class="input-box">
          <div>
            <ion-label class="text-label">Old Password</ion-label>
            <base-input
              type="password"
              placeholder="Enter old password"
              class="password__input"
              v-model:value="passwordInput"
              :error-message="passwordInputError"
              :disabled="loading"
            />
          </div>
          <div>
            <ion-label class="text-label">New Password</ion-label>
            <base-input
              v-model:value="newPasswordInput"
              :error-message="newPasswordError"
              :disabled="loading"
              type="password"
              placeholder="Enter new password"
              class="password__input"
            />
          </div>
          <div>
            <ion-label class="text-label">Confirm Password</ion-label>
            <base-input
              v-model:value="passwordConfirmationInput"
              :error-message="passwordConfirmationError"
              type="password"
              placeholder="Confirm password"
              class="password__input"
            />
          </div>
        </div>
      </div>
      <div class="d-flex align-items-center justify-content-end save-box">
        <ion-button
          @click="onSubmit"
          :disabled="loading || !isValidForm"
        >
          Save
        </ion-button>
      </div>
    </div>
    <div class="content-box column-box">
      <div class="d-flex justify-content-between align-items-center ">
        <div>
          <ion-title class="content-box__title">
            Two-factor Authentication
          </ion-title>
          <ion-label>Add an extra later of security to block unauthorized access and protect your account.</ion-label>
        </div>
        <ion-button>Enable</ion-button>
      </div>
      <div class="content-box__line"/>
      <div class="d-flex justify-content-between aling-items-center justify-content-center option-box">
        <div>
          <ion-text>Authentication app code</ion-text><br/>
          <ion-label color="medium">Enter a code generated by authenticator app to confirm it’s you.</ion-label>
        </div>
        <ion-toggle></ion-toggle>
      </div>
      <div class="d-flex justify-content-between aling-items-center justify-content-center option-box">
        <div>
          <ion-text>Sms recovery</ion-text><br/>
          <ion-label color="medium">Receive a six digit code by text message to confirm it’s you</ion-label>
        </div>
        <ion-toggle></ion-toggle>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
	IonTitle,
  IonButton,
  IonLabel,
  IonToggle,
} from "@ionic/vue";
import BaseInput from "@/general/components/base/BaseInput.vue";
import { useMutation, useQuery } from "@vue/apollo-composable";
import { MeDocument, UpdatePasswordDocument } from "@/generated/graphql";
import { useField } from "vee-validate";
import { passwordSchema } from "@/validations/authValidations";
import { computed } from "vue";
import { humanizeString } from "@/utils/textUtils";
import { toastController } from "@ionic/vue";

const { mutate, onDone, loading, error } = useMutation(UpdatePasswordDocument);

const { value: passwordInput, errorMessage: passwordInputError } =
  useField<string>("password", passwordSchema);

const { value: newPasswordInput, errorMessage: newPasswordError } =
  useField<string>("new password", passwordSchema);

const {
  value: passwordConfirmationInput,
  errorMessage: passwordConfirmationError,
} = useField<string>(
  "password confirmation",
  (inputValue) => inputValue === newPasswordInput.value
);

const errorMessage = computed(() => {
  return humanizeString(
    error.value?.message || "Something went wrong. Please try again."
  );
});

const showToast = async (message: string, style = "success") => {
  const toast = await toastController.create({
    message: message,
    duration: 2000,
    icon: "assets/icon/success.svg",
    cssClass: `${style}-toast`,
  });
  return toast.present();
};

onDone(({ data }) => {
  showToast(data.updatePassword.message);
  passwordInput.value = "";
  newPasswordInput.value = "";
  passwordConfirmationInput.value = "";
});

const isValidForm = computed(() =>
  hasPassword.value
    ? !passwordInputError.value &&
      !passwordConfirmationError.value &&
      !newPasswordError.value &&
      passwordInput.value &&
      passwordConfirmationInput.value &&
      newPasswordInput.value
    : !passwordConfirmationError.value &&
      !newPasswordError.value &&
      passwordConfirmationInput.value &&
      newPasswordInput.value
);

const onSubmit = () => {
  if (isValidForm.value) {
    mutate({
      input: {
        old_password: hasPassword.value ? passwordInput.value : "",
        password: newPasswordInput.value,
        password_confirmation: passwordConfirmationInput.value,
      },
    }).catch(() => {
      showToast(errorMessage.value, "danger");
    });
  }
};

const { result: userResult } = useQuery(MeDocument);

const hasPassword = computed<boolean>(() => userResult.value?.me.has_password);
</script>

<style lang="scss" scoped>

.title {
  padding: 0;
  font-size: 28px;
  line-height: 1.3;
  font-weight: 400;
  margin-bottom: 24px;
}
.top-buttons {
  display: flex;
  justify-content: space-between;
}
.dashboard-btn {
  margin-top: 10px;
}
.content-box {
  background-color: #0000001a;
  margin-top: 20px;
  margin-bottom: 20px;
  padding-top: 23px;
  padding-left: 35px;
  padding-right: 6px;
  padding-bottom: 20px;

  &__top {
    display: flex;
    padding-right: 13px;
  }

  &__title {
    padding: 0;
  }

  &__button {
    max-width: 73px;
    max-height: 36px;
  }

  &__line {
    margin-left: -20px;
    height: 2px;
    background-color: var(--gray-600);
  }
}
.column-box {
  display: flex;
  flex-direction: column;
  gap: 14px;
}
.save-box {
  padding-top: 26px;
  padding-right: 20px;
}
.input-box {
  display: flex;
  flex-direction: column;
  gap: 10px;
  max-width: 473px;
}
.text-label {
  color: #FFFFFF6a;
}
.text-value {
  color: var(--grey-text);
  background-color: var(--gray-600);
  font: 600 18px/1 var(--ion-font-family);
}
.option-box {
  padding: 10px;
}

ion-button {
  color: var(--ion-color-medium);
  max-height: 40px;
}
ion-input {
  border: solid;
  border-color: #FFFFFF6a;
  border-radius: 8px;
  border-width: 1px;
  margin-top: 6px;
  margin-bottom: 6px;
  --placeholder-color: var(--ion-color-medium);
}
ion-label {
  font: 400 14px/1 var(--ion-font-family);
}
ion-toggle {
  height: 28px;
  width: 48px;
  padding-bottom: 0;
  padding-top: 0;
  --handle-height: 24px;
  --handle-width: 24px;
  --handle-spacing: 3px;
  --background: var(--gray-600);
  --background-checked: var(--gold);
  --handle-background: var(--gray-700);
  --handle-background-checked: var(--gray-700);
}
</style>
