query countries (
  $name: String
  $first: Int!
  $page: Int
) {
  countries (
    name: $name
    first: $first
    page: $page
  ) {
    data {
      id
      name
    }
    paginatorInfo {
      total
    }
  }
}
