name: Build and Upload to Google Play Internal Testing

on:
  push:
    branches:
      - DEV

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      OVERRIDE_JAVA_VERSION: 17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install --legacy-peer-deps
          npm install -g ionic
          npm run build
          npm run android        

      - name: Load signing key content into environment variable
        run: |
          export SIGNING_KEY=$(cat android/app/keystore/spotter_dev.jks | base64 -w 0)
        shell: bash
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Assemble Release Bundle
        run: |
          chmod +x ./gradlew
          ./gradlew bundleRelease --no-daemon -Pandroid.injected.signing.store.file=android/app/keystore/spotter_dev.jks -Pandroid.injected.signing.store.password=spotter -Pandroid.injected.signing.key.alias=spotter -Pandroid.injected.signing.key.password=spotter
        working-directory: ./android

      - name: Deploy to Google Play Internal Testing
        run: |
          echo $GOOGLE_PLAY_JSON > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project your-project-id
          gcloud app android-apps upload path/to/your/project/android/app/build/outputs/bundle/release/app-release.aab --internal-testing
          gcloud app android-apps upload path/to/your/project/android/app/build/outputs/apk/release/app-release.apk --internal-testing
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
