name: Build and Upload to Google Play Internal Testing

on:
  push:
    branches:
      - DEV

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install --legacy-peer-deps
          
      - name: Ionic production build
        run: |
          ionic build --prod

      - name: Build Android .aab and .apk
        run: |
          npx cap sync android
          npx cap add android
          npx cap copy android
          npx cap open android

      - name: Decrypt signing key
        run: |
          mkdir -p app/keystore
          echo "$SIGNING_KEY" | base64 -d > app/keystore/spotter_dev.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
        working-directory: ./android

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Google Play Internal Testing
        run: |
          echo $GOOGLE_PLAY_JSON > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project spotter-fitness-d49be
          gcloud app android-apps upload app/build/outputs/bundle/release/app-release.aab --internal-testing
          gcloud app android-apps upload app/build/outputs/apk/release/app-release.apk --internal-testing
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
