on:
  push:
    branches:
      - DEV

name: Build SpotterFitness Android 

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install -g @ionic/cli

      - run: npm install

      - run: ionic build --prod

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ionic-artifacts
          path: www

      - name: Push to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ./www/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v0.0.1
          release_name: Release v0.0.1
